export const domainsData = {
  "vlsi": {
    id: "vlsi",
    title: "VLSI Design Architecture",
    iconId: "cpu",
    length: "40h Intensive",
    modules: 34,
    tag: "Hardware Core",
    focus: "Chip Design, RTL Coding, FPGA",
    techs: ["Verilog", "SystemVerilog", "ASIC"],
    syllabus: ["Digital Logic & CMOS", "Verilog RTL Design", "SystemVerilog Verification", "FPGA Prototyping", "Static Timing Analysis"],
    about: "Very-Large-Scale Integration (VLSI) is the process of creating an integrated circuit (IC) by combining millions or billions of MOS transistors onto a single chip. It is the absolute foundation of all modern electronics, from your smartphone to high-performance AI clusters.",
    whyChoose: "The world is experiencing a critical pivot towards specialized silicon. General-purpose CPUs are no longer sufficient for AI and machine learning workloads. Mastering VLSI puts you at the bleeding edge of the hardware revolution, designing the physical neural engines of tomorrow.",
    marketGrowth: "The global semiconductor market is projected to reach $1 Trillion by 2030. Unprecedented demand from the Electric Vehicle (EV), Artificial Intelligence, and Aerospace sectors has created an absolute vacuum of skilled ASIC/FPGA engineers.",
    hiring: "Entry-level compensation for RTL engineers has surged 40% globally since 2020. Top recruiters aggressively seeking these skills include NVIDIA, Apple, Intel, AMD, and Qualcomm."
  },
  "mongodb-django": {
    id: "mongodb-django",
    title: "MongoDB & Django Systems",
    iconId: "database",
    length: "40h Intensive",
    modules: 33,
    tag: "Backend Scalability",
    focus: "NoSQL, REST APIs, Microservices",
    techs: ["MongoDB", "Django", "Python"],
    syllabus: ["Python & Django Fundamentals", "RESTful API Architecture", "MongoDB Data Modeling", "Authentication & Security", "Microservices Deployment"],
    about: "This domain focuses on engineering robust, high-throughput backend systems. By pairing the rapid development capabilities of Python's Django framework with the massive horizontal scalability of MongoDB, you build systems capable of handling millions of concurrent operations.",
    whyChoose: "Data is the new oil, but unstructured data is the raw crude. Relational databases choke under modern, varied data loads. Mastering NoSQL (MongoDB) combined with a hardened backend framework (Django) makes you an architectural powerhouse capable of scaling startups to enterprise levels.",
    marketGrowth: "The cloud computing and backend infrastructure market is scaling at a 15% CAGR. Companies are migrating away from monolithic SQL structures to agile, microservice-based NoSQL architectures to handle Big Data.",
    hiring: "Backend architects utilizing Python and NoSQL are among the most consistently hired engineers worldwide. Major players like Instagram, Spotify, and Uber heavily rely on these exact tech stacks."
  },
  "embedded": {
    id: "embedded",
    title: "Embedded Systems Engineering",
    iconId: "cpu",
    length: "40h Intensive",
    modules: 26,
    tag: "Hardware Core",
    focus: "IoT, Microcontrollers, RTOS",
    techs: ["C++", "RTOS", "ARM Cortex"],
    syllabus: ["C/C++ for Embedded", "ARM Cortex-M Architecture", "RTOS Concepts & FreeRTOS", "I2C, SPI, UART Protocols", "IoT Edge Computing"],
    about: "Embedded systems sit at the critical junction between hardware and software. This is the engineering of dedicated computing systems within larger mechanical or electrical systems, specifically focusing on microcontrollers and Real-Time Operating Systems (RTOS).",
    whyChoose: "If you want your code to move physical objects, fly drones, or control medical devices, this is the domain. Embedded engineers write the incredibly efficient, low-latency C++ code that keeps the physical world functioning without crashing.",
    marketGrowth: "The Internet of Things (IoT) and automotive electronics (EV/Autonomous driving) are driving a $150 Billion expansion in the embedded market. Every physical device is becoming smart, requiring an embedded system.",
    hiring: "Massive talent shortage. Automotive giants (Tesla, Ford), aerospace (SpaceX, Boeing), and consumer electronics (Sony, Samsung) are fighting over a limited pool of engineers who truly understand memory-safe embedded C/C++."
  },
  "fullstack": {
    id: "fullstack",
    title: "Full Stack NodeJS Architecture",
    iconId: "code",
    length: "45h Intensive",
    modules: 42,
    tag: "Full Stack",
    focus: "React, Node, CI/CD pipelines",
    techs: ["React", "Node.js", "TypeScript"],
    syllabus: ["Advanced JavaScript/TypeScript", "React & State Management", "Node.js & Express Backends", "SQL & NoSQL Integration", "Docker & CI/CD Pipelines"],
    about: "End-to-end web architecture. You will master the entire modern JavaScript ecosystem, using TypeScript to enforce strict typing across both the React frontend and the highly asynchronous Node.js backend. This is the art of building complete platforms.",
    whyChoose: "Full Stack engineers are the ultimate generalists and the backbone of the tech industry. You don't just build a piece of the puzzle; you build, deploy, and scale the entire product yourself. It is the fastest path to becoming a CTO or technical founder.",
    marketGrowth: "The web development sector continues its unstoppable growth. The shift towards Single Page Applications (SPAs) and Serverless architectures has cemented the JavaScript/TypeScript ecosystem as the universal language of the web.",
    hiring: "Unmatched volume of opportunities. From Y-Combinator startups to Fortune 500 enterprises, every company needs full-stack engineers to maintain and scale their web products."
  },
  "ai": {
    id: "ai",
    title: "Applied Data Science & AI",
    iconId: "network",
    length: "50h Intensive",
    modules: 40,
    tag: "Intelligence",
    focus: "Deep Learning, PyTorch, MLOps",
    techs: ["Python", "PyTorch", "TensorFlow"],
    syllabus: ["Data Engineering & Pandas", "Machine Learning Algorithms", "Deep Learning & Neural Networks", "PyTorch & Computer Vision", "MLOps & Model Deployment"],
    about: "This is not just data analysis; this is Applied Artificial Intelligence. You will engineer deep neural networks using PyTorch, process massive datasets, and deploy intelligent models to production environments using modern MLOps practices.",
    whyChoose: "AI is no longer a research experiment; it is an industrial requirement. By mastering deep learning and the mathematics behind neural architectures, you position yourself at the forefront of the most significant technological paradigm shift since the internet.",
    marketGrowth: "The AI market is experiencing hyper-growth, projected to surpass $1.5 Trillion by 2030. The integration of LLMs (Large Language Models) and computer vision into legacy systems is driving unprecedented enterprise spending.",
    hiring: "Data Scientists and ML Engineers are commanding the highest compensation packages in the industry. OpenAI, Google DeepMind, Meta, and virtually every hedge fund are aggressively recruiting PyTorch experts."
  },
  "react-native": {
    id: "react-native",
    title: "React Native Ecosystems",
    iconId: "zap",
    length: "35h Intensive",
    modules: 28,
    tag: "Frontend Mobile",
    focus: "Cross-platform, Animations, Redux",
    techs: ["React Native", "Redux", "Swift"],
    syllabus: ["React Native Architecture", "Navigation & State (Redux)", "Native Device Features", "Complex Animations (Reanimated)", "App Store Deployment"],
    about: "Engineering cross-platform mobile applications that feel entirely native. You will bypass the need to write separate Swift and Kotlin codebases, using React Native to deliver 60fps mobile experiences to both iOS and Android from a single codebase.",
    whyChoose: "Mobile traffic dominates global internet usage. Companies cannot afford to maintain two separate mobile engineering teams. React Native solves this billion-dollar problem, making engineers who can write smooth, performant cross-platform code incredibly valuable.",
    marketGrowth: "The mobile app market generates over $400 Billion annually. As hardware limits are removed, the demand for complex, heavily animated, and high-performance mobile applications continues to skyrocket.",
    hiring: "React Native is heavily backed by Meta and utilized by giants like Shopify, Discord, and Uber Eats. The demand for engineers who can bridge the gap between web React and native mobile APIs is at an all-time high."
  }
};
