export const domainsData = {
  "vlsi": {
    id: "vlsi",
    title: "VLSI Design Architecture",
    iconId: "cpu",
    length: "40h Intensive",
    modules: 34,
    tag: "Hardware Core",
    focus: "Chip Design, RTL Coding, FPGA",
    techs: ["Verilog", "SystemVerilog", "ASIC"],
    syllabus: ["Digital Logic & CMOS", "Verilog RTL Design", "SystemVerilog Verification", "FPGA Prototyping", "Static Timing Analysis"],
    about: "Traditional university curricula lack the silicon-level rigor required by modern semiconductor firms. In this domain, you won't just study theory; you will engineer verifiable ASIC/FPGA prototypes. This is the cryptographic proof of hardware competence that recruiters at NVIDIA and Intel are actively searching for.",
    whyChoose: "Degrees no longer signal hardware competence. Recruiters are aggressively filtering for candidates who can demonstrate actual RTL design and verification capabilities. Building a verified VLSI portfolio bypasses the initial technical screening rounds entirely.",
    marketGrowth: "The global semiconductor market is scaling towards $1 Trillion. General-purpose engineers are common; specialized silicon engineers are exceptionally rare. The industry faces an absolute vacuum of verified RTL talent to support the AI hardware boom.",
    hiring: "Lead recruiters from Apple, Qualcomm, and Intel prioritize candidates with demonstrable FPGA and SystemVerilog projects over generic electronics degrees. Start proving your competence."
  },
  "mongodb-django": {
    id: "mongodb-django",
    title: "MongoDB & Django Systems",
    iconId: "database",
    length: "40h Intensive",
    modules: 33,
    tag: "Backend Scalability",
    focus: "NoSQL, REST APIs, Microservices",
    techs: ["MongoDB", "Django", "Python"],
    syllabus: ["Python & Django Fundamentals", "RESTful API Architecture", "MongoDB Data Modeling", "Authentication & Security", "Microservices Deployment"],
    about: "Recruiters cannot evaluate a backend engineer based on a certificate. You must prove you can engineer high-throughput systems capable of scaling. This track focuses on building industry-grade REST APIs and microservices using Django and MongoDB, directly addressing the core competencies technical recruiters filter for.",
    whyChoose: "Every company needs scalable data infrastructure, but few entry-level engineers can prove they know how to build it. A verified NoSQL and Django microservice architecture in your portfolio serves as undeniable evidence of your backend engineering capability.",
    marketGrowth: "Companies are aggressively migrating away from monolithic structures. Engineering managers are actively hiring candidates who can handle unstructured data at scale. The demand for verified Python/NoSQL architects is outpacing the supply of capable graduates.",
    hiring: "Skip the generic HR queue. Startups and enterprise tech companies heavily recruit engineers whose portfolios demonstrate real-world scaling solutions, RESTful design, and secure authentication pipelines."
  },
  "embedded": {
    id: "embedded",
    title: "Embedded Systems Engineering",
    iconId: "cpu",
    length: "40h Intensive",
    modules: 26,
    tag: "Hardware Core",
    focus: "IoT, Microcontrollers, RTOS",
    techs: ["C++", "RTOS", "ARM Cortex"],
    syllabus: ["C/C++ for Embedded", "ARM Cortex-M Architecture", "RTOS Concepts & FreeRTOS", "I2C, SPI, UART Protocols", "IoT Edge Computing"],
    about: "The gap between writing software and controlling physical hardware is massive. Standard resumes fail to capture this expertise. We guide you to engineer memory-safe, low-latency C++ code on RTOS, creating a verifiable portfolio of hardware-level control systems that tech recruiters trust.",
    whyChoose: "Embedded systems require a zero-margin-of-error approach. Demonstrating a functional RTOS project on an ARM Cortex architecture proves you possess the rigorous engineering mindset that aerospace, automotive, and robotics companies demand.",
    marketGrowth: "The $150 Billion expansion in IoT and Autonomous Vehicles requires engineers who can write efficient edge-computing code. There is a massive talent shortage of verified C/C++ developers who understand real-time constraints.",
    hiring: "Automotive giants (Tesla, Ford) and aerospace firms (SpaceX) are fighting over a limited pool of engineers. A verified embedded portfolio is the strongest signal you can send to hardware engineering managers."
  },
  "fullstack": {
    id: "fullstack",
    title: "Full Stack NodeJS Architecture",
    iconId: "code",
    length: "45h Intensive",
    modules: 42,
    tag: "Full Stack",
    focus: "React, Node, CI/CD pipelines",
    techs: ["React", "Node.js", "TypeScript"],
    syllabus: ["Advanced JavaScript/TypeScript", "React & State Management", "Node.js & Express Backends", "SQL & NoSQL Integration", "Docker & CI/CD Pipelines"],
    about: "Technical recruiters spend seconds scanning resumes for modern stack proficiency. A generic CS degree doesn't prove you can deploy full-stack applications. In this domain, you build and deploy end-to-end TypeScript architectures, providing undeniable, verifiable proof of your full-stack capabilities.",
    whyChoose: "Full Stack engineers are the backbone of modern tech, but the junior market is saturated with unverified talent. A robust, deployed React and Node.js platform with complete CI/CD pipelines instantly elevates your profile past the initial ATS filters.",
    marketGrowth: "The universal language of the web is JavaScript/TypeScript. The shift towards serverless architectures and SPAs requires engineers who understand the entire request lifecycle. Hiring managers are desperate for engineers who can execute end-to-end.",
    hiring: "Unmatched volume of opportunities. Y-Combinator startups and Fortune 500 enterprises alike use our verifiable portfolios to source full-stack engineers who can contribute to production immediately."
  },
  "ai": {
    id: "ai",
    title: "Applied Data Science & AI",
    iconId: "network",
    length: "50h Intensive",
    modules: 40,
    tag: "Intelligence",
    focus: "Deep Learning, PyTorch, MLOps",
    techs: ["Python", "PyTorch", "TensorFlow"],
    syllabus: ["Data Engineering & Pandas", "Machine Learning Algorithms", "Deep Learning & Neural Networks", "PyTorch & Computer Vision", "MLOps & Model Deployment"],
    about: "The AI industry does not hire based on textbook knowledge; they hire based on deployed models. This track forces you to engineer PyTorch neural networks and implement MLOps pipelines. It is the ultimate proof of competence for recruiters seeking Applied AI talent.",
    whyChoose: "AI is no longer theoretical; it's industrial. Demonstrating the ability to build, train, and deploy deep learning models using industry-standard tools like PyTorch separates you from candidates who only understand high-level concepts.",
    marketGrowth: "The integration of LLMs and deep learning into enterprise systems is driving unprecedented hiring. Engineering managers lack reliable ways to verify AI skills; a cryptographically verified ML portfolio solves their sourcing problem.",
    hiring: "Data Scientists and ML Engineers command the highest compensation packages globally. Tech giants and hedge funds aggressively recruit engineers who possess verified MLOps and PyTorch expertise."
  },
  "react-native": {
    id: "react-native",
    title: "React Native Ecosystems",
    iconId: "zap",
    length: "35h Intensive",
    modules: 28,
    tag: "Frontend Mobile",
    focus: "Cross-platform, Animations, Redux",
    techs: ["React Native", "Redux", "Swift"],
    syllabus: ["React Native Architecture", "Navigation & State (Redux)", "Native Device Features", "Complex Animations (Reanimated)", "App Store Deployment"],
    about: "Mobile engineering teams need proof that you can handle native bridging and 60fps animations. This domain guides you through building complex cross-platform applications, creating a verifiable portfolio that proves you can deliver production-ready mobile experiences to recruiters.",
    whyChoose: "Companies cannot afford to maintain separate iOS and Android teams. A verifiable project demonstrating mastery of React Native, Redux, and Reanimated proves you can solve this billion-dollar business problem.",
    marketGrowth: "The mobile app market requires engineers who can build complex, heavily animated interfaces efficiently. As hardware limits disappear, the demand for verified cross-platform engineers continues to skyrocket.",
    hiring: "Meta, Shopify, and Discord heavily rely on React Native. Recruiters from these mobile-first companies use verified portfolios to identify engineers who can bridge the gap between web React and native mobile APIs."
  }
};

export default domainsData;
