export const domainsData: Record<string, any> = {
  // 1. Software Engineering & Web
  "mongodb-django": {
    id: "mongodb-django",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-01-15",
    title: "MongoDB With Django",
    tag: "Backend Systems",
    iconId: "database",
    length: "33 Lessons",
    focus: "NoSQL Database Integration",
    techs: ["MongoDB", "Django", "Python", "REST APIs"],
    modules: 33,
    about: "Master the integration of Django's robust web framework with MongoDB's flexible NoSQL architecture to build highly scalable backend systems capable of handling massive data throughput.",
    whyChoose: "Traditional relational databases struggle with unstructured data at scale. This combination allows for rapid iteration and massive horizontal scaling.",
    marketGrowth: "NoSQL database usage is growing at 31% CAGR as applications demand more flexible schema designs.",
    hiring: "Companies like Meta, Google, and hyper-growth startups actively recruit engineers capable of designing NoSQL-backed Django microservices.",
    syllabus: ["NoSQL Architecture Principles", "Django ORM with MongoDB", "Advanced Query Optimization", "REST Framework Integration", "Horizontal Scaling & Sharding"]
  },
  "mongodb-nodejs": {
    id: "mongodb-nodejs",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-01-29",
    title: "MongoDB With NodeJS",
    tag: "MERN Stack Foundations",
    iconId: "code",
    length: "33 Lessons",
    focus: "High-Concurrency Backend",
    techs: ["MongoDB", "Node.js", "Express", "Mongoose"],
    modules: 33,
    about: "Engineer event-driven, high-concurrency backend services using Node.js and MongoDB. Focus on asynchronous programming, API architecture, and real-time data flow.",
    whyChoose: "Node.js combined with MongoDB provides a unified JavaScript ecosystem across the entire stack, drastically reducing context switching and improving development velocity.",
    marketGrowth: "Node.js remains the most used web framework globally, driving demand for specialized backend architects.",
    hiring: "Heavily utilized by Netflix, Uber, and PayPal for microservices architecture.",
    syllabus: ["Event-Driven Architecture", "MongoDB Aggregation Pipeline", "Authentication & JWT", "Real-time WebSockets", "Performance Profiling"]
  },
  "advanced-java": {
    id: "advanced-java",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-02-12",
    title: "Advanced Java Programming",
    tag: "Enterprise Systems",
    iconId: "cpu",
    length: "32 Lessons",
    focus: "Enterprise-Grade Architecture",
    techs: ["Java", "JVM", "Multithreading", "Spring"],
    modules: 32,
    about: "Delve deep into the JVM, multithreading, and advanced object-oriented design patterns required to build mission-critical enterprise applications used by global financial institutions.",
    whyChoose: "Java remains the absolute gold standard for high-security, high-reliability enterprise systems.",
    marketGrowth: "Continuous demand from banking, insurance, and large-scale enterprise sectors.",
    hiring: "Top investment banks and fortune 500 companies relentlessly seek advanced Java architects.",
    syllabus: ["JVM Internals & Garbage Collection", "Advanced Multithreading", "Design Patterns", "Microservices with Spring", "Enterprise Security"]
  },
  "fullstack": {
    id: "fullstack",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-02-26",
    title: "Full Stack Web Development",
    tag: "End-to-End Architecture",
    iconId: "code",
    length: "31 Lessons",
    focus: "Scalable Full Stack Systems",
    techs: ["React", "Node.js", "PostgreSQL", "Redis"],
    modules: 31,
    about: "A rigorous, end-to-end engineering protocol covering frontend optimization, backend architecture, caching layers, and database optimization.",
    whyChoose: "True full-stack architects are rare. Understanding how the frontend impacts the backend database queries is a critical skill for senior roles.",
    marketGrowth: "Full stack engineering consistently ranks among the top 3 most in-demand roles globally.",
    hiring: "Universal demand across all tech tiers, from early-stage startups to FAANG.",
    syllabus: ["System Design Fundamentals", "Advanced React Patterns", "Backend Optimization", "Caching with Redis", "CI/CD Deployment Pipelines"]
  },
  "web-development": {
    id: "web-development",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-03-12",
    title: "Web Development",
    tag: "Frontend Core",
    iconId: "code",
    length: "33 Lessons",
    focus: "Modern Web Interfaces",
    techs: ["HTML5", "CSS3", "JavaScript", "Web APIs"],
    modules: 33,
    about: "Master the foundational technologies of the web. Build performant, accessible, and highly interactive user interfaces from the ground up without relying heavily on bloated frameworks.",
    whyChoose: "A deep understanding of the DOM and vanilla JavaScript is what separates average developers from elite frontend engineers.",
    marketGrowth: "The foundation of all web technologies ensures permanent relevance in the job market.",
    hiring: "Required baseline for any specialized frontend or full-stack role.",
    syllabus: ["Advanced DOM Manipulation", "CSS Architecture & Variables", "Web Accessibility (a11y)", "Browser Rendering Optimization", "Modern JavaScript (ES6+)"]
  },
  "reactjs": {
    id: "reactjs",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-03-26",
    title: "ReactJS",
    tag: "Client-Side Engineering",
    iconId: "code",
    length: "34 Lessons",
    focus: "Component Architecture",
    techs: ["React", "Redux", "Hooks", "Next.js"],
    modules: 34,
    about: "Engineer complex, state-driven client applications. Focus intensely on reconciliation, render optimization, and scalable component architectures used in large codebases.",
    whyChoose: "React dominates the frontend landscape. Deep mastery of its internals is required to build performant apps at scale.",
    marketGrowth: "React holds the largest market share among frontend frameworks, continuing to grow with Server Components.",
    hiring: "The standard for frontend development at companies like Meta, Airbnb, and Shopify.",
    syllabus: ["Reconciliation & Virtual DOM", "Advanced Hooks & Custom Hooks", "State Management Strategies", "Performance Tuning", "Server-Side Rendering Context"]
  },
  "mysql-spring-boot": {
    id: "mysql-spring-boot",
    category: "Software Engineering & Web",
    image: "/images/domains/software_web.png",
    dateAdded: "2023-04-09",
    title: "MySQL With Spring Boot",
    tag: "Microservices",
    iconId: "database",
    length: "33 Lessons",
    focus: "Relational Data Systems",
    techs: ["Spring Boot", "MySQL", "JPA/Hibernate", "Java"],
    modules: 33,
    about: "Design robust, transactional microservices using Spring Boot and MySQL. Focus on ACID compliance, complex relational queries, and resilient API architectures.",
    whyChoose: "The industry standard for mission-critical transactional systems that require strict data integrity.",
    marketGrowth: "Spring Boot remains the dominant framework for Java-based microservices architecture.",
    hiring: "Crucial for fintech, healthcare, and enterprise software domains.",
    syllabus: ["Spring Data JPA", "Advanced MySQL Indexing", "Transaction Management", "Microservices Security", "API Gateway Integration"]
  },

  // 2. Data Science & AI
  "ai-python": {
    id: "ai-python",
    category: "Data Science & AI",
    image: "/images/domains/data_science.png",
    dateAdded: "2023-04-23",
    title: "Artificial Intelligence With Python",
    tag: "AI Engineering",
    iconId: "cpu",
    length: "29 Lessons",
    focus: "Intelligent Systems",
    techs: ["Python", "TensorFlow", "Neural Networks", "NLP"],
    modules: 29,
    about: "Engineer intelligent systems capable of perception, reasoning, and learning. Transition from basic algorithms to deep neural networks using industry-standard Python libraries.",
    whyChoose: "AI is reshaping every industry. Engineering reliable, scalable AI models is the highest-leverage skill in the modern economy.",
    marketGrowth: "The AI sector is experiencing exponential growth, outstripping available talent supply.",
    hiring: "Intense competition among top tech firms to acquire competent AI engineers.",
    syllabus: ["Search Algorithms & Heuristics", "Deep Learning Fundamentals", "Computer Vision Architectures", "Natural Language Processing", "Model Deployment & MLOps"]
  },
  "data-science-python": {
    id: "data-science-python",
    category: "Data Science & AI",
    image: "/images/domains/data_science.png",
    dateAdded: "2023-05-07",
    title: "Data Science With Python",
    tag: "Statistical Modeling",
    iconId: "database",
    length: "28 Lessons",
    focus: "Data Pipelines & Analysis",
    techs: ["Pandas", "NumPy", "Scikit-Learn", "SQL"],
    modules: 28,
    about: "Master the complete data pipeline: from extraction and cleaning to advanced statistical modeling and visualization, driving rigorous business decisions.",
    whyChoose: "Data is the new oil, but only if you have the engineering rigor to refine it into actionable intelligence.",
    marketGrowth: "Data science roles are projected to grow 36% over the next decade.",
    hiring: "Ubiquitous demand across finance, e-commerce, and logistics sectors.",
    syllabus: ["Data Manipulation with Pandas", "Statistical Inference", "Predictive Modeling", "Feature Engineering", "Data Visualization"]
  },
  "machine-learning": {
    id: "machine-learning",
    category: "Data Science & AI",
    image: "/images/domains/data_science.png",
    dateAdded: "2023-05-21",
    title: "Machine Learning With Python",
    tag: "Predictive Systems",
    iconId: "zap",
    length: "28 Lessons",
    focus: "Algorithm Optimization",
    techs: ["Python", "PyTorch", "Algorithms", "Mathematics"],
    modules: 28,
    about: "Focus heavily on the mathematics and algorithmic implementation of machine learning models. Build, tune, and deploy predictive systems from scratch.",
    whyChoose: "Understanding the underlying math allows you to optimize models far beyond what basic library wrappers permit.",
    marketGrowth: "Machine Learning Engineers are among the highest-paid technical roles globally.",
    hiring: "Required by specialized AI labs and data-driven product companies.",
    syllabus: ["Linear Algebra & Calculus for ML", "Supervised Learning Algorithms", "Unsupervised Learning", "Hyperparameter Optimization", "Ensemble Methods"]
  },
  "business-analytics": {
    id: "business-analytics",
    category: "Data Science & AI",
    image: "/images/domains/data_science.png",
    dateAdded: "2023-06-04",
    title: "Business Analytics",
    tag: "Data-Driven Strategy",
    iconId: "network",
    length: "33 Lessons",
    focus: "Strategic Intelligence",
    techs: ["Tableau", "PowerBI", "SQL", "Excel"],
    modules: 33,
    about: "Bridge the gap between raw data and executive strategy. Architect analytics dashboards and reporting pipelines that drive billion-dollar business decisions.",
    whyChoose: "The ability to translate complex data into business strategy is a rare, highly valued hybrid skill.",
    marketGrowth: "Exponential increase as companies pivot to data-driven decision making.",
    hiring: "Consulting firms, venture capital, and corporate strategy teams.",
    syllabus: ["Advanced SQL for Analytics", "Dashboard Architecture", "KPI Engineering", "A/B Testing Frameworks", "Executive Communication"]
  },

  // 3. Hardware, IoT & Core Engineering
  "vlsi": {
    id: "vlsi",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-06-18",
    title: "VLSI Design Architecture",
    tag: "Silicon Engineering",
    iconId: "cpu",
    length: "34 Lessons",
    focus: "Chip Design & Verification",
    techs: ["Verilog", "SystemVerilog", "ASIC", "FPGA"],
    modules: 34,
    about: "Master the microarchitecture of modern silicon. From RTL design using Verilog to advanced physical verification, engineer the hardware that powers the digital world.",
    whyChoose: "Hardware is experiencing a renaissance. Specialized silicon (AI chips, custom CPUs) requires elite VLSI engineers.",
    marketGrowth: "The semiconductor industry is doubling in size, driven by AI and IoT demands.",
    hiring: "NVIDIA, Intel, AMD, and Apple Silicon aggressively recruit top VLSI talent.",
    syllabus: ["Digital Logic & RTL Design", "SystemVerilog & UVM", "FPGA Prototyping", "Static Timing Analysis", "Physical Design & Verification"]
  },
  "embedded": {
    id: "embedded",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-07-02",
    title: "Embedded Systems Using Proteus",
    tag: "Microcontroller Systems",
    iconId: "cpu",
    length: "26 Lessons",
    focus: "Hardware-Software Interface",
    techs: ["C/C++", "Microcontrollers", "Proteus", "RTOS"],
    modules: 26,
    about: "Engineer highly optimized, low-latency firmware for bare-metal systems. Utilize Proteus software for rigorous simulation before hardware deployment.",
    whyChoose: "The intersection of hardware and software is critical for automotive, aerospace, and medical devices.",
    marketGrowth: "Steady, robust growth fueled by the automation and automotive sectors.",
    hiring: "Automotive companies, defense contractors, and consumer electronics firms.",
    syllabus: ["Bare-metal C Programming", "Microcontroller Architecture", "Interrupts & Timers", "Hardware Simulation in Proteus", "Real-Time Operating Systems (RTOS)"]
  },
  "ic-engine": {
    id: "ic-engine",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-07-16",
    title: "IC Engine",
    tag: "Mechanical Core",
    iconId: "zap",
    length: "31 Lessons",
    focus: "Thermal Systems & Thermodynamics",
    techs: ["Thermodynamics", "Fluid Mechanics", "CAD", "Simulation"],
    modules: 31,
    about: "Deep dive into the thermodynamics, fluid mechanics, and material science behind Internal Combustion Engines. Focus on efficiency optimization and emission reduction technologies.",
    whyChoose: "Fundamental mechanical engineering principles that translate to aerospace, power generation, and advanced propulsion systems.",
    marketGrowth: "Critical for heavy machinery, aerospace, and specialized automotive sectors.",
    hiring: "Aerospace firms, heavy industries, and specialized automotive manufacturers.",
    syllabus: ["Advanced Thermodynamics", "Combustion Dynamics", "Emission Control Systems", "Engine Simulation", "Performance Optimization"]
  },
  "car-design": {
    id: "car-design",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-07-30",
    title: "Car Design",
    tag: "Automotive Architecture",
    iconId: "network",
    length: "29 Lessons",
    focus: "Aerodynamics & Chassis",
    techs: ["AutoCAD", "CATIA", "Aerodynamics", "Materials"],
    modules: 29,
    about: "Architect the vehicles of the future. Integrate aerodynamic principles, structural integrity, and ergonomic design using industry-standard CAD and simulation tools.",
    whyChoose: "Automotive design is undergoing a massive shift with the advent of EVs and autonomous vehicles.",
    marketGrowth: "High demand for engineers who understand both traditional mechanical design and modern aerodynamics.",
    hiring: "Top automotive OEMs and specialized EV startups.",
    syllabus: ["Automotive Aerodynamics", "Chassis Design & Dynamics", "Material Selection", "Crash Simulation", "Ergonomics & Packaging"]
  },
  "hybrid-ev": {
    id: "hybrid-ev",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-08-13",
    title: "Hybrid and Electric Vehicle",
    tag: "Next-Gen Automotive",
    iconId: "zap",
    length: "29 Lessons",
    focus: "Battery Systems & Powertrains",
    techs: ["Battery Tech", "Power Electronics", "Motors", "BMS"],
    modules: 29,
    about: "Engineer the electric revolution. Master high-voltage battery management systems, power electronics, and motor control algorithms for next-generation EVs.",
    whyChoose: "The global transition to electric vehicles is creating an unprecedented demand for specialized EV engineers.",
    marketGrowth: "EV engineering is one of the fastest-growing sectors in the global economy.",
    hiring: "Tesla, Rivian, traditional OEMs pivoting to EV, and battery technology firms.",
    syllabus: ["Battery Management Systems (BMS)", "Power Electronics & Inverters", "Electric Motor Control", "Thermal Management", "Charging Infrastructure Protocol"]
  },
  "robotics": {
    id: "robotics",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-08-27",
    title: "Robotics",
    tag: "Autonomous Systems",
    iconId: "cpu",
    length: "31 Lessons",
    focus: "Kinematics & Control",
    techs: ["ROS", "Python", "Kinematics", "Sensors"],
    modules: 31,
    about: "Architect autonomous robotic systems. Master kinematics, dynamics, sensor fusion, and control theory using the Robot Operating System (ROS).",
    whyChoose: "Robotics represents the convergence of software, AI, and mechanical engineering.",
    marketGrowth: "Explosive growth in logistics automation, manufacturing, and autonomous navigation.",
    hiring: "Automation firms, logistics giants (Amazon), and autonomous vehicle companies.",
    syllabus: ["Robot Kinematics & Dynamics", "Robot Operating System (ROS)", "Sensor Fusion & Computer Vision", "Path Planning Algorithms", "Control Theory"]
  },
  "iot": {
    id: "iot",
    category: "Hardware, IoT & Core Engineering",
    image: "/images/domains/hardware_iot.png",
    dateAdded: "2023-09-10",
    title: "Internet Of Things",
    tag: "Connected Systems",
    iconId: "network",
    length: "28 Lessons",
    focus: "Edge Computing & Telemetry",
    techs: ["MQTT", "Edge Computing", "Sensors", "Networking"],
    modules: 28,
    about: "Engineer secure, highly scalable networks of connected devices. Focus on edge computing, low-power telemetry protocols (MQTT), and IoT security.",
    whyChoose: "IoT is connecting the physical world to the digital infrastructure, requiring engineers who understand both hardware constraints and cloud scalability.",
    marketGrowth: "Billions of devices are coming online, driving massive demand for secure IoT architecture.",
    hiring: "Smart home companies, industrial automation, and cloud providers.",
    syllabus: ["IoT Communication Protocols", "Edge Device Programming", "Data Telemetry & Ingestion", "IoT Security Protocols", "Cloud Integration for IoT"]
  },

  // 4. Cloud Computing & Cyber Security
  "azure": {
    id: "azure",
    category: "Cloud Computing & Cyber Security",
    image: "/images/domains/cloud_security.png",
    dateAdded: "2023-09-24",
    title: "Microsoft Azure Cloud Computing",
    tag: "Enterprise Cloud",
    iconId: "network",
    length: "27 Lessons",
    focus: "Cloud Architecture",
    techs: ["Azure", "Docker", "Kubernetes", "Terraform"],
    modules: 27,
    about: "Architect secure, scalable enterprise infrastructure on Microsoft Azure. Focus on advanced networking, serverless compute, and infrastructure as code.",
    whyChoose: "Azure is the dominant cloud platform for enterprise companies, offering deep integration with the Microsoft ecosystem.",
    marketGrowth: "Azure continues to capture significant market share in the enterprise cloud sector.",
    hiring: "Fortune 500 companies, government agencies, and large-scale enterprises.",
    syllabus: ["Azure Virtual Networks", "Serverless Architecture", "Azure Kubernetes Service (AKS)", "Infrastructure as Code (IaC)", "Enterprise Identity & Security"]
  },
  "aws": {
    id: "aws",
    category: "Cloud Computing & Cyber Security",
    image: "/images/domains/cloud_security.png",
    dateAdded: "2023-10-08",
    title: "Amazon Web Services Cloud Computing",
    tag: "Hyperscale Cloud",
    iconId: "network",
    length: "30 Lessons",
    focus: "Global Infrastructure",
    techs: ["AWS", "EC2", "S3", "Lambda"],
    modules: 30,
    about: "Design hyper-scalable, fault-tolerant systems on AWS. Master distributed system architecture, serverless event-driven paradigms, and advanced cloud networking.",
    whyChoose: "AWS remains the largest and most widely used cloud provider globally.",
    marketGrowth: "Cloud computing is the backbone of the modern internet, with AWS leading the charge.",
    hiring: "Startups, tech giants, and almost every company migrating to the cloud.",
    syllabus: ["AWS VPC Architecture", "Serverless & AWS Lambda", "Database Scaling on RDS & DynamoDB", "High Availability & Fault Tolerance", "Cost Optimization"]
  },
  "cyber-security": {
    id: "cyber-security",
    category: "Cloud Computing & Cyber Security",
    image: "/images/domains/cloud_security.png",
    dateAdded: "2023-10-22",
    title: "Cyber Security Using Kali Linux",
    tag: "Offensive Security",
    iconId: "code",
    length: "25 Lessons",
    focus: "Penetration Testing",
    techs: ["Kali Linux", "Network Security", "Cryptography", "PenTesting"],
    modules: 25,
    about: "Master offensive security techniques. Conduct rigorous penetration testing, vulnerability assessment, and exploit development using industry-standard tools in Kali Linux.",
    whyChoose: "As infrastructure scales, security vulnerabilities multiply. Offensive security engineers are critical to uncovering flaws before malicious actors do.",
    marketGrowth: "Cybersecurity demand continues to vastly outpace supply due to increasing global threats.",
    hiring: "Defense contractors, financial institutions, and specialized security firms.",
    syllabus: ["Network Reconnaissance", "Vulnerability Exploitation", "Web Application Security", "Cryptography Principles", "Incident Response Protocols"]
  },
  "blockchain": {
    id: "blockchain",
    category: "Cloud Computing & Cyber Security",
    image: "/images/domains/cloud_security.png",
    dateAdded: "2023-11-05",
    title: "Blockchain Development",
    tag: "Decentralized Systems",
    iconId: "database",
    length: "31 Lessons",
    focus: "Smart Contracts & Web3",
    techs: ["Solidity", "Ethereum", "Web3.js", "Cryptography"],
    modules: 31,
    about: "Architect decentralized applications (dApps) and secure smart contracts. Understand consensus mechanisms, cryptographic primitives, and the Web3 ecosystem.",
    whyChoose: "Blockchain offers a paradigm shift in trust and data verification, requiring engineers with a deep understanding of cryptography and distributed systems.",
    marketGrowth: "High growth in DeFi, supply chain verification, and decentralized identity.",
    hiring: "Fintech companies, Web3 startups, and enterprise blockchain consortiums.",
    syllabus: ["Cryptography & Consensus Mechanisms", "Smart Contract Development (Solidity)", "Web3 Integration", "DeFi Protocols", "Blockchain Security Auditing"]
  },

  // 5. Design & UI/UX
  "graphic-design": {
    id: "graphic-design",
    category: "Design & UI/UX",
    image: "/images/domains/design_ui.png",
    dateAdded: "2023-11-19",
    title: "Graphic Design",
    tag: "Visual Communication",
    iconId: "code", // Can map to a better icon in UI
    length: "32 Lessons",
    focus: "Brand & Identity Systems",
    techs: ["Photoshop", "Illustrator", "Typography", "Color Theory"],
    modules: 32,
    about: "Master the principles of visual communication. Engineer compelling brand identities, typography systems, and high-impact visual assets.",
    whyChoose: "Exceptional design is the foundation of brand trust and user engagement.",
    marketGrowth: "Steady demand across all sectors for high-quality visual communication.",
    hiring: "Design agencies, marketing firms, and in-house corporate design teams.",
    syllabus: ["Design Theory & Psychology", "Vector Graphics Engineering", "Advanced Typography", "Brand Identity Systems", "Digital Asset Production"]
  },
  "ui-ux": {
    id: "ui-ux",
    category: "Design & UI/UX",
    image: "/images/domains/design_ui.png",
    dateAdded: "2023-12-03",
    title: "UI/UX",
    tag: "User Experience Architecture",
    iconId: "code",
    length: "33 Lessons",
    focus: "Human-Computer Interaction",
    techs: ["Figma", "Prototyping", "Wireframing", "User Research"],
    modules: 33,
    about: "Design intuitive, conversion-optimized user experiences based on rigorous behavioral psychology and data-driven user research.",
    whyChoose: "The barrier to entry for software is lower than ever; superior UX is often the only competitive differentiator.",
    marketGrowth: "Explosive growth as companies recognize the ROI of frictionless user experiences.",
    hiring: "Tech product companies, design consultancies, and specialized digital agencies.",
    syllabus: ["UX Research Methodologies", "Information Architecture", "Wireframing & Prototyping in Figma", "Interaction Design", "Usability Testing"]
  },
  "autocad": {
    id: "autocad",
    category: "Design & UI/UX",
    image: "/images/domains/design_ui.png",
    dateAdded: "2023-12-17",
    title: "AutoCAD Using Autodesk Software",
    tag: "Precision Drafting",
    iconId: "cpu",
    length: "29 Lessons",
    focus: "2D & 3D Architectural Design",
    techs: ["AutoCAD", "Drafting", "3D Modeling", "Architecture"],
    modules: 29,
    about: "Engineer precise 2D drafting and 3D modeling for architectural, civil, and mechanical engineering projects using industry-standard Autodesk software.",
    whyChoose: "AutoCAD remains the foundational tool for architectural and engineering documentation globally.",
    marketGrowth: "Consistent demand tied to global infrastructure and real estate development.",
    hiring: "Architecture firms, civil engineering contractors, and manufacturing companies.",
    syllabus: ["Precision 2D Drafting", "Isometric Projection", "3D Modeling Fundamentals", "Engineering Drawing Standards", "Rendering & Layout"]
  },

  // 6. Business, Management & Finance
  "stock-marketing": {
    id: "stock-marketing",
    category: "Business, Management & Finance",
    image: "/images/domains/business_finance.png",
    dateAdded: "2023-12-31",
    title: "Stock Marketing",
    tag: "Financial Markets",
    iconId: "network",
    length: "32 Lessons",
    focus: "Market Dynamics & Trading",
    techs: ["Technical Analysis", "Fundamental Analysis", "Risk Mgmt"],
    modules: 32,
    about: "Analyze financial markets with algorithmic precision. Master fundamental valuation, technical charting, and rigorous risk management protocols.",
    whyChoose: "Understanding capital markets is essential for financial engineering and strategic investment.",
    marketGrowth: "Increased retail and institutional participation in global equity markets.",
    hiring: "Investment firms, proprietary trading desks, and financial consultancies.",
    syllabus: ["Market Microstructure", "Fundamental Valuation Models", "Technical Charting Strategies", "Risk & Portfolio Management", "Algorithmic Trading Concepts"]
  },
  "marketing-management": {
    id: "marketing-management",
    category: "Business, Management & Finance",
    image: "/images/domains/business_finance.png",
    dateAdded: "2024-01-14",
    title: "Marketing Management",
    tag: "Strategic Growth",
    iconId: "network",
    length: "32 Lessons",
    focus: "Brand Strategy & Positioning",
    techs: ["Strategy", "Analytics", "Consumer Behavior", "Campaigns"],
    modules: 32,
    about: "Architect comprehensive growth strategies. Bridge the gap between product engineering and market penetration through data-driven consumer psychology.",
    whyChoose: "The best product fails without a precise, execution-oriented go-to-market strategy.",
    marketGrowth: "High demand for data-literate marketing executives who can drive measurable ROI.",
    hiring: "FMCG companies, tech startups, and global marketing agencies.",
    syllabus: ["Market Segmentation & Positioning", "Consumer Psychology", "Pricing Strategy", "Integrated Campaign Architecture", "Marketing Analytics"]
  },
  "human-resource": {
    id: "human-resource",
    category: "Business, Management & Finance",
    image: "/images/domains/business_finance.png",
    dateAdded: "2024-01-28",
    title: "Human Resource Management And Analytics",
    tag: "People Operations",
    iconId: "users",
    length: "32 Lessons",
    focus: "Talent Strategy & Analytics",
    techs: ["HR Analytics", "Talent Acquisition", "Retention Strategy"],
    modules: 32,
    about: "Transform HR from an administrative function into a strategic, data-driven powerhouse. Master predictive talent analytics and organizational design.",
    whyChoose: "Human capital is the most expensive and valuable asset in tech; optimizing it requires rigorous analytics.",
    marketGrowth: "Rapid transition from traditional HR to data-driven People Operations.",
    hiring: "Enterprise organizations and hyper-growth tech companies.",
    syllabus: ["Strategic Talent Acquisition", "Performance Metrics & Analytics", "Organizational Behavior", "Compensation Engineering", "Predictive Attrition Modeling"]
  },
  "digital-marketing": {
    id: "digital-marketing",
    category: "Business, Management & Finance",
    image: "/images/domains/business_finance.png",
    dateAdded: "2024-02-11",
    title: "Digital Marketing Using SEO And Marketing Automation Tools",
    tag: "Growth Engineering",
    iconId: "network",
    length: "29 Lessons",
    focus: "SEO & Automation Pipelines",
    techs: ["SEO", "Automation", "Analytics", "CRM"],
    modules: 29,
    about: "Engineer scalable acquisition funnels. Master technical SEO, programmatic marketing automation, and complex CRM integrations to drive exponential growth.",
    whyChoose: "Growth engineering relies on automated, scalable systems rather than manual effort.",
    marketGrowth: "The shift to digital-first customer acquisition continues unabated.",
    hiring: "E-commerce giants, SaaS companies, and digital growth agencies.",
    syllabus: ["Technical SEO Architecture", "Marketing Automation Workflows", "CRM Integration (HubSpot/Salesforce)", "Conversion Rate Optimization (CRO)", "Advanced Web Analytics"]
  },
  "finance": {
    id: "finance",
    category: "Business, Management & Finance",
    image: "/images/domains/business_finance.png",
    dateAdded: "2024-02-25",
    title: "Finance",
    tag: "Corporate Finance",
    iconId: "database",
    length: "32 Lessons",
    focus: "Financial Modeling & Strategy",
    techs: ["Financial Modeling", "Valuation", "Accounting", "M&A"],
    modules: 32,
    about: "Master corporate finance, advanced financial modeling, and strategic valuation. Build the rigorous quantitative foundation required for high-stakes financial strategy.",
    whyChoose: "Capital allocation and financial strategy dictate the survival and growth of any enterprise.",
    marketGrowth: "Continuous demand for quantitatively rigorous financial analysts.",
    hiring: "Investment banking, private equity, and corporate finance departments.",
    syllabus: ["Advanced Financial Modeling", "Corporate Valuation Methods", "Mergers & Acquisitions (M&A)", "Capital Structure Optimization", "Financial Risk Management"]
  },

  // 7. Specialized Sciences
  "construction-planning": {
    id: "construction-planning",
    category: "Specialized Sciences",
    image: "/images/domains/specialized_science.png",
    dateAdded: "2024-03-10",
    title: "Construction Planning And Structural Analysis",
    tag: "Civil Infrastructure",
    iconId: "network",
    length: "29 Lessons",
    focus: "Structural Integrity & Project Mgmt",
    techs: ["Structural Analysis", "Project Planning", "AutoCAD", "Materials"],
    modules: 29,
    about: "Engineer the physical world. Master advanced structural analysis, material load dynamics, and complex large-scale construction project management.",
    whyChoose: "Infrastructure projects require zero-margin-for-error engineering and rigorous planning.",
    marketGrowth: "Driven by global infrastructure development and urbanization trends.",
    hiring: "Civil engineering firms, government infrastructure departments, and global construction contractors.",
    syllabus: ["Structural Dynamics", "Load Bearing Analysis", "Large-Scale Project Scheduling", "Construction Material Science", "Safety Protocol Engineering"]
  },
  "nanoscience": {
    id: "nanoscience",
    category: "Specialized Sciences",
    image: "/images/domains/specialized_science.png",
    dateAdded: "2024-03-24",
    title: "Nanoscience And Nanotechnology",
    tag: "Atomic Engineering",
    iconId: "zap",
    length: "32 Lessons",
    focus: "Nanomaterials & Quantum Effects",
    techs: ["Nanomaterials", "Quantum Physics", "Chemistry", "Fabrication"],
    modules: 32,
    about: "Engineer at the atomic level. Explore quantum effects, nanomaterial synthesis, and applications in electronics, medicine, and energy storage.",
    whyChoose: "Nanotechnology is the frontier of material science, enabling breakthroughs from ultra-dense batteries to targeted medicine.",
    marketGrowth: "High growth in specialized R&D, pharmaceuticals, and advanced electronics.",
    hiring: "Advanced R&D labs, semiconductor manufacturers, and biotech firms.",
    syllabus: ["Quantum Mechanics Basics", "Nanomaterial Synthesis", "Characterization Techniques (SEM/TEM)", "Nanoelectronics", "Nanomedicine Applications"]
  },
  "genetic-engineering": {
    id: "genetic-engineering",
    category: "Specialized Sciences",
    image: "/images/domains/specialized_science.png",
    dateAdded: "2024-04-07",
    title: "Genetic Engineering",
    tag: "Bio-Architecture",
    iconId: "network",
    length: "32 Lessons",
    focus: "CRISPR & Synthetic Biology",
    techs: ["CRISPR", "Genomics", "Bioinformatics", "Molecular Biology"],
    modules: 32,
    about: "Architect the fundamental code of life. Master CRISPR-Cas9, genomic sequencing, and synthetic biology to solve critical challenges in healthcare and agriculture.",
    whyChoose: "Biology has become an engineering discipline. Editing DNA allows for unprecedented solutions to disease and food security.",
    marketGrowth: "Biotech is experiencing a golden age, driven by recent advances in gene editing tools.",
    hiring: "Pharmaceutical companies, agritech startups, and genetic research institutes.",
    syllabus: ["Molecular Biology Fundamentals", "CRISPR & Gene Editing", "Genomic Sequencing", "Bioinformatics Pipelines", "Synthetic Biology Engineering"]
  }
};
