export const reviews = [
  { name: "Siddharth V.", role: "Software Engineer", initials: "SV", bg: "from-[#E6C875] to-yellow-800", quote: "Incredible platform. Building a cryptographically verified PyTorch MLOps pipeline on Ved got me direct inbound from a Lead Architect at a top firm. The best upskilling experience I've had.", rating: 5, source: "Google" },
  { name: "Priya M.", role: "Senior Architect", initials: "PM", bg: "from-gray-300 dark:from-white to-gray-500 dark:to-gray-400", quote: "Ved stripped away the generic fluff. Having a verifiable React and Node.js microservice architecture in my portfolio bypassed the ATS filters entirely. I skipped two technical rounds.", rating: 5, source: "Google" },
  { name: "Rahul D.", role: "Embedded Lead", initials: "RD", bg: "from-[#E6C875]/60 to-yellow-900", quote: "Recruiters don't care about your coursework; they care if you can write memory-safe code. The verified FreeRTOS portfolio I built here proved my competence instantly.", rating: 5, source: "Google" },
  { name: "Ananya K.", role: "Data Scientist", initials: "AK", bg: "from-gray-200 dark:from-gray-300 to-gray-400 dark:to-gray-600", quote: "Traditional placements were a dead end. The Execution Protocol is intense, but the verified proof of skill gave me the visibility I needed to land a role building scalable ML models.", rating: 5, source: "Google" },
  { name: "Vikram S.", role: "Full Stack Dev", initials: "VS", bg: "from-[#E6C875] to-yellow-800", quote: "I was stuck in a low-paying job. The curriculum here is so industry-aligned that my final project was directly used as a proof-of-concept during my interview. Unmatched quality.", rating: 5, source: "Google" },
  { name: "Neha T.", role: "Product Manager", initials: "NT", bg: "from-gray-300 dark:from-white to-gray-500 dark:to-gray-400", quote: "Not just for devs! Understanding the architecture to this depth allowed me to transition into a highly technical PM role. The cryptographic proof of projects is a game changer.", rating: 5, source: "Google" },
  { name: "Arjun P.", role: "Cloud Engineer", initials: "AP", bg: "from-[#E6C875]/60 to-yellow-900", quote: "The AWS and Kubernetes deployment projects are brutal but exactly what the industry demands. I secured a 2x salary hike purely based on my verifiable portfolio.", rating: 5, source: "Google" },
  { name: "Riya C.", role: "UI/UX Designer", initials: "RC", bg: "from-gray-200 dark:from-gray-300 to-gray-400 dark:to-gray-600", quote: "Integrating my designs into real, scalable front-ends gave me a huge edge. The recruiters were blown away by the live, verifiable links instead of just a Figma file.", rating: 5, source: "Google" }
];

export default reviews;
